site_name: 'Skill Plotter'
site_description: 'Generate skill plots for your CV'
site_author: Andre Wohnsland
copyright: © Copyright 2023, Andre Wohnsland & contributors
repo_url: https://github.com/AndreWohnsland/skillplotter
repo_name: 'GitHub skill-plotter'
nav:
  - Home: index.md
  - Usage: usage.md
  - Development: development.md
markdown_extensions:
  # - mkdocs-click
  - toc:
      permalink: '#'
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
  name: material
  custom_dir: docs/overrides
  logo: img/skillplotter.svg
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: img/favicon.ico
plugins:
  - search:
      separator: '[\s\-\.]+'
extra_css:
  - css/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
