[project]
name = "skill-plotter"
version = "0.4.2"
description = "CLI tool to generate a plot of your skills"
authors = [{ name = "Andre Wohnsland", email = "50302161+AndreWohnsland@users.noreply.github.com" }]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = [
    "skill",
    "plot",
    "cli",
    "tool",
    "cv",
    "resume",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "matplotlib>=3.11.0,<4",
    "typer>=0.26.8",
    "jsonschema>=4.26.0,<5",
]

[project.urls]
Homepage = "https://skillplotter.readthedocs.io/"
Repository = "https://github.com/AndreWohnsland/skillplotter"
Documentation = "https://skillplotter.readthedocs.io"

[project.scripts]
skill-plotter = "skill_plotter.main:app"

[dependency-groups]
dev = [
    "zensical>=0.0.47",
    "jupyterlab>=4.4.2",
    "ruff>=0.15.21",
    "ty>=0.0.59",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["skill_plotter"]
module-root = ""

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = [
  "B", # flake8-bugbear
  "C", # Convention
  "D", # pydocstyle 
  "E", # pycodestyle
  "F", # Pyflakes
  "I", # isort 
  "ICN001", # {name} should be imported as {asname},
  "R", # Refactor
  "RUF", # Ruff
  "SIM", # flake8-simplify
  "UP", # pyupgrade
  "W", # Pylint (Warning)
]
ignore = [
  "D100", # Missing docstring in public module
  "D101", # Missing docstring in public class
  "D102", # Missing docstring in public method
  "D103",  # Missing docstring in public function
  "D104", # Missing docstring in public package
  "D105", # Missing docstring in magic method
  "D203", # 1 blank line required before class docstring
  "D213", # Multi-line docstring summary should start at the second line
]
