name: Build & publish to pipy
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false

jobs:
  publish-service-client-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish PyPi package
        uses: code-specialist/pypi-poetry-publish@v1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_DIRECTORY: './skill_plotter/'
          PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          PUBLISH_REGISTRY: 'https://test.pypi.org/simple/'
